language: java
before_install:
- cp .travis.maven.settings.xml $HOME/.m2/settings.xml
branches:
  only:
  - master
  - /^\d+\.\d+$/
jobs:
  include:
    - stage: test
      name: "Unit tests"
      script: mvn -B -DtestLogLevel=OFF test
      jdk: oraclejdk8
    - name: "Integration tests"
      script: mvn -B -DtestLogLevel=OFF -DskipUnitTests verify
      jdk: oraclejdk8
    - stage: deploy
      name: "Deploy to Sonatype's snapshots repository"
      if: type != pull_request
      script: bash .travis.deploy.artifacts.sh
notifications:
  email:
    recipients:
      - vertx3-ci@googlegroups.com
    on_success: always
    on_failure: always
