language: java
before_install:
- cp .travis.maven.settings.xml $HOME/.m2/settings.xml
jdk:
- oraclejdk8
install: true
script:
- set -e
- mvn -DtestLogLevel=OFF clean verify -B
branches:
  only:
  - master
notifications:
  email:
    recipients:
      - vertx3-ci@googlegroups.com
    on_success: always
    on_failure: always
