language: java
before_install:
- cp .travis.maven.settings.xml $HOME/.m2/settings.xml
jdk:
- oraclejdk8
install: true
branches:
  only:
  - master
jobs:
  include:
    - stage: test
      name: "Unit tests"
      script: mvn -B -DtestLogLevel=OFF test
    - name: "Integration tests"
      script: mvn -B -DtestLogLevel=OFF -DskipUnitTests verify
notifications:
  email:
    recipients:
      - vertx3-ci@googlegroups.com
    on_success: always
    on_failure: always
